# -*- coding: utf-8 -*-

"""
This file is part of LAMIA.

    LAMIA is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    LAMIA is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <https://www.gnu.org/licenses/>.

"""
"""
  * Copyright (c) 2017-2020 ARTELIA Commit <lamia@arteliagroup.com>
  * 
  * SPDX-License-Identifier: GPL-3.0-or-later
  * License-Filename: LICENSING.md
 """


import os, importlib, tempfile, pprint, shutil
from collections import OrderedDict
import sys, glob, inspect, logging, textwrap
import Lamia
from ..abstractlibslamia import AbstractLibsLamia

import qgis
from qgis.PyQt import QtGui, uic, QtCore, QtXml

import pandas as pd
import numpy as np

# dictionary with code of deformations as key
# first value is the factor or alpha parameter
# second value is L if you multiply by observated length or P if you multiply by P parameter
# we sum and threshold to defined a value in [1, 2, 3, 4]
all_ensablement_indicators = {
    "ENS4":
    {
        "BACA"	:[0, "P"],	# RUPTURE / EFFONDREMENT - RUPTURE
        "BACB"	:[0, "P"],	# EFFONDREMENT PARTIEL
        "BACC"	:[3, "P"],	# EFFONDREMENT TOTAL
        "BADA"	:[0, "P"],	# MACONNERIE DEPLACEE
        "BADC"	:[0, "P"],	# AFFAISSEMENT DE RADIER
        "BADD"	:[3, "P"],	# EFFONDREMENT
        "BAFA"	:[1, "L"],	# DEGRADATION DE SURFACE - RUGOSITE ACCRUE
        "BAFAA"	:[1, "L"],	# DEGRADATION DE SURFACE - RUGOSITE ACCRUE - ABRASION
        "BAFAB"	:[1, "L"],	# DEGRADATION DE SURFACE - RUGOSITE ACCRUE - ATTAQUE CHIMIQUE - GENERALE
        "BAFAC"	:[1, "L"],	# DEGRADATION DE SURFACE - RUGOSITE ACCRUE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFAD"	:[1, "L"],	# DEGRADATION DE SURFACE - RUGOSITE ACCRUE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFAE"	:[1, "L"],	# DEGRADATION DE SURFACE - RUGOSITE ACCRUE - AUCUNE CAUSE EVIDENTE
        "BAFB"	:[1, "L"],	# DEGRADATION DE SURFACE - ECAILLAGE CORROSION
        "BAFBA"	:[1, "L"],	# DEGRADATION DE SURFACE - ECAILLAGE - ABRASION
        "BAFBB"	:[1, "L"],	# DEGRADATION DE SURFACE - ECAILLAGE - ATTAQUE CHIMIQUE - GENERALE
        "BAFBC"	:[1, "L"],	# DEGRADATION DE SURFACE - ECAILLAGE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFBD"	:[1, "L"],	# DEGRADATION DE SURFACE - ECAILLAGE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFBE"	:[1, "L"],	# DEGRADATION DE SURFACE - ECAILLAGE - AUCUNE CAUSE EVIDENTE
        "BAFC"	:[1, "L"],	#  DEGRADATION DE SURFACE - GRANULATS EXPOSES
        "BAFCA"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS EXPOSES - ABRASION
        "BAFCB"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS EXPOSES - ATTAQUE CHIMIQUE - GENERALE
        "BAFCC"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS EXPOSES - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFCD"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS EXPOSES - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFCE"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS EXPOSES - AUCUNE CAUSE EVIDENTE
        "BAFD"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS DECHAUSSES
        "BAFDA"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS DECHAUSSES - ABRASION
        "BAFDB"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS DECHAUSSES - ATTAQUE CHIMIQUE - GENERALE
        "BAFDC"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS DECHAUSSES - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFDD"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS DECHAUSSES - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFDE"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS DECHAUSSES - AUCUNE CAUSE EVIDENTE
        "BAFE"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS MANQUANTS
        "BAFEA"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS MANQUANTS - ABRASION
        "BAFEB"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS MANQUANTS - ATTAQUE CHIMIQUE - GENERALE
        "BAFEC"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS MANQUANTS - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFED"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS MANQUANTS - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFEE"	:[1, "L"],	# DEGRADATION DE SURFACE - GRANULATS MANQUANTS - AUCUNE CAUSE EVIDENTE
        "BAFF"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE VISIBLE
        "BAFFA"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE VISIBLE - ABRASION
        "BAFFB"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE VISIBLE - ATTAQUE CHIMIQUE - GENERALE
        "BAFFC"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE VISIBLE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFFD"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE VISIBLE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFFE"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE VISIBLE - AUCUNE CAUSE EVIDENTE
        "BAFG"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE DEPASSANT SURFACE
        "BAFGA"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE DEPASSANT SURFACE - ABRASION
        "BAFGB"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE DEPASSANT SURFACE - ATTAQUE CHIMIQUE - GENERALE
        "BAFGC"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE DEPASSANT SURFACE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFGD"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE DEPASSANT SURFACE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFGE"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE DEPASSANT SURFACE - AUCUNE CAUSE EVIDENTE
        "BAFH"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE CORRODEE
        "BAFHA"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE CORRODEE - ABRASION
        "BAFHB"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE CORRODEE - ATTAQUE CHIMIQUE - GENERALE
        "BAFHC"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE CORRODEE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFHD"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE CORRODEE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFHE"	:[1, "L"],	# DEGRADATION DE SURFACE - ARMATURE CORRODEE - AUCUNE CAUSE EVIDENTE
        "BAFI"	:[1, "L"],	# DEGRADATION DE SURFACE - PAROI MANQUANTE
        "BAFIA"	:[1, "L"],	# DEGRADATIONS DE SURFACE - PAROI MANQUANTE - ABRASION
        "BAFIB"	:[1, "L"],	# DEGRADATION DE SURFACE - PAROI MANQUANTE - ATTAQUE CHIMIQUE - GENERALE
        "BAFIC"	:[1, "L"],	# DEGRADATION DE SURFACE - PAROI MANQUANTE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFID"	:[1, "L"],	# DEGRADATION DE SURFACE - PAROI MANQUANTE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFIE"	:[1, "L"],	# DEGRADATIONS DE SURFACE - PAROI MANQUANTE - AUCUNE CAUSE EVIDENTE
        "BAFJ"	:[1, "L"],	# DEGRADATION DE SURFACE - PRODUITS CORROSIFS EN SURFACE
        "BAFJA"	:[1, "L"],	# DEGRADATION DE SURFACE - PRODUITS CORROSIFS EN SURFACE - ABRASION
        "BAFJB"	:[1, "L"],	# DEGRADATION DE SURFACE - PRODUITS CORROSIFS EN SURFACE - ATTAQUE CHIMIQUE - GENERALE
        "BAFJC"	:[1, "L"],	# DEGRADATION DE SURFACE - PRODUITS CORROSIFS EN SURFACE - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFJD"	:[1, "L"],	# DEGRADATION DE SURFACE - PRODUITS CORROSIFS EN SURFACE - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFJE"	:[1, "L"],	# DEGRADATION DE SURFACE - PRODUITS CORROSIFS EN SURFACE - AUCUNE CAUSE EVIDENTE
        "BAFKA"	:[1, "L"],	# DEGRADATIONS DE SURFACE - POINCONNEMENT
        "BAFZ"	:[1, "L"],	# DEGRADATION DE SURFACE - AUTRES DEGRADATIONS
        "BAFZA"	:[1, "L"],	# DEGRADATION DE SURFACE - AUTRES DEGRADATIONS - ABRASION
        "BAFZB"	:[1, "L"],	# DEGRADATION DE SURFACE - AUTRES DEGRADATIONS - ATTAQUE CHIMIQUE - GENERALE
        "BAFZC"	:[1, "L"],	# DEGRADATION DE SURFACE - AUTRES DEGRADATIONS - ATTAQUE CHIMIQUE - DUE A H2SO4 - AU DESSUS DU NIVEAU DE L'EAU
        "BAFZD"	:[1, "L"],	# DEGRADATION DE SURFACE - AUTRES DEGRADATIONS - ATTAQUE CHIMIQUE - DUE AUX EU - AU DESSOUS DU NIVEAU DE L'EAU
        "BAFZE"	:[1, "L"],	# DEGRADATION DE SURFACE - AUTRES DEGRADATIONS - AUCUNE CAUSE EVIDENTE
        "BAG" 	:[2, "P"],	# BRANCHEMENT PENETRANT
        "BAIA"	:[0, "P"],	# ANNEAU D'ETANCHEITE
        "BAIAA"	:[0, "P"],	# JOINT D'ETANCHEITE APPARENT - ANNEAU D'ETANCHEITE AVEC BOUCLE DEPLACEE MAIS NE DEPASSANT PAS DANS LA CANALISATION
        "BAIAB"	:[0, "P"],	# JOINT D'ETANCHEITE APPARENT - PENETRANT MAIS NON ROMPU (AU-DESSUS DE LA MEDIANE)
        "BAIAC"	:[0, "P"],	# JOINT D'ETANCHEITE APPARENT - PENETRANT MAIS NON ROMPU (AU-DESSOUS DE LA MEDIANE)
        "BAIAD"	:[0, "P"],	# JOINT D'ETANCHEITE APPARENT - PENETRANT - ROMPU
        "BAIZ"	:[0, "P"],	# AUTRE ELEMENT D'ETANCHEITE
        "BAJA"	:[0, "P"],	# DEBOITEMENT LONGITUDINAL
        "BAJB"	:[0, "P"],	# DECENTRAGE RADIAL
        "BAJC"	:[0, "P"],	# DEVIATION ANGULAIRE
        "BAKA"	:[0, "P"],	# REVETEMENT DE CANALISATION  DETACHE
        "BAKB"	:[1, "P"],	# DECOLORATION DU REVETEMENT
        "BAKC"	:[1, "P"],	# EXTREMITE DU REVETEMENT DEFECTUEUSE
        "BAKD"	:[1, "P"],	# REVETEMENT ONDULE
        "BAKDA"	:[1, "P"],	# REVETEMENT ONDULE - LONGITUDINALEMENT
        "BAKDB"	:[1, "P"],	# REVETEMENT ONDULE - CIRCONFERENTIELLEMENT
        "BAKDC"	:[1, "P"],	# REVETEMENT ONDULE - COMPLEXE
        "BAKE"	:[0, "P"],	# REVETEMENT CLOQUE
        "BAKZ"	:[0, "P"],	# AUTRE DE FAUT DE REVETEMENT
        "BBAA"	:[2, "P"],	# GROSSE RACINE ISOLEE
        "BBAB"	:[0, "P"],	# RADICELLES
        "BBAC"	:[2, "P"],	# ENSEMBLE COMPLEXE DE RACINES
        "BBBA"	:[0, "P"],	# DEPOTS ADHERENTS - CONCRETION
        "BBBB"	:[0, "P"],	# DEPOTS ADHERENTS - GRAISSE
        "BBBC"	:[1, "P"],	# DEPOTS ADHERENTS - ENCRASSEMENT
        "BBBZ"	:[0, "P"],	# DEPOTS ADHERENTS - AUTRE
        "BBCA"	:[0, "P"],	# DEPOTS - FINS
        "BBCB"	:[0, "P"],	# DEPOTS -  GROSSIERS
        "BBCC"	:[1, "P"],	# DEPOTS - DURS OU COMPACTES
        "BBCZ"	:[0, "P"],	# DEPOTS - AUTRES
        "BBDA"	:[1, "P"],	# ENTREE DE TERRE - SABLE
        "BBDB"	:[1, "P"],	# ENTREE DE TERRE - TOURBE
        "BBDC"	:[1, "P"],	# ENTREE DE TERRE - MATERIAU FIN
        "BBDD"	:[1, "P"],	# ENTREE DE TERRE - GRAVIER
        "BBDZ"	:[1, "P"],	# ENTREE DE TERRE - AUTRE
        "BBEA"	:[2, "P"],	# AUTRES OBSTABLES - BRIQUETAGE OU MACONNERIE GISANT SUR LE RADIER
        "BBEB"	:[2, "P"],	# AUTRES OBSTABLES - FRAGMENT DE CONDUITE BRISEE GISANT SUR LE RADIER
        "BBEC"	:[2, "P"],	# AUTRES OBSTACLES - OBJET SUR LE RADIER
        "BBED"	:[2, "P"],	# AUTRES OBSTABLES - OBSTACLE DEPASSANT DE LA PAROI
        "BBEE"	:[2, "P"],	# AUTRES OBSTACLES - OBSTACLE COINCE DANS L'ASSEMBLAGE
        "BBEF"	:[2, "P"],	# AUTRES OBSTABLES - OBSTACLE TRAVERSANT UN RACCORDEMENT OU UNE CONDUITE DE RACCORDEMENT
        "BBEG"	:[2, "P"],	# AUTRES OBSTACLES - CONDUITE EXTERNE OU CABLES INSERES DANS LA CANALISATION
        "BBEH"	:[2, "P"],	# AUTRES OBSTABLES - OBSTACLE INTEGRE A LA STRUCTURE
        "BBEZ"	:[2, "P"],	# AUTRES OBSTACLES - AUTRE
        "BCC"	:[3, "P"],	# COURBURE COLLECTEUR
        "BCCA"	:[3, "P"],	# COURBURE COLLECTEUR - VERS LA GAUCHE
        "BCCAA"	:[3, "P"],	# COURBURE COLLECTEUR - VERS LA GAUCHE - VERS LE HAUT
        "BCCAB"	:[3, "P"],	# COURBURE COLLECTEUR - VERS LA GAUCHE - VERS LE BAS
        "BCCB"	:[3, "P"],	# COURBURE COLLECTEUR - VERS LA DROITE
        "BCCBA"	:[3, "P"],	# COURBURE COLLECTEUR - VERS LA DROITE - VERS LE HAUT
        "BCCBB"	:[3, "P"],	# COURBURE COLLECTEUR - VERS LA DROITE - VERS LE BAS
        "D"   	:[2, "P"],	# CONTRE PENTE
        "DACB"	:[0, "P"],	# EFFONDREMENT PARTIEL
        "DBAB"	:[0, "P"],	# RADICELLES
        "DBAC"	:[2, "P"],	# ENSEMBLE COMPLEXE DE RACINES
        "DBCB"	:[0, "P"],	# DEPOTS -  GROSSIERS
        "DBEG"	:[0, "P"],	# AUTRES OBSTACLES - CONDUITE EXTERNE OU CABLES INSERES DANS LA CANALISATION
    },
}
