FROM ubuntu:focal  AS build

# set work directory
WORKDIR /usr/src/app

# uncomment for install behind artelias proxy
# ARG http_proxy=http://10.1.3.48:3128
# ARG https_proxy=http://10.1.3.48:3128

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# general dependancies
RUN apt-get update && apt-get install apt-utils sudo dialog dos2unix wget -y
# skipping prompt for keyboard conf
RUN DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration -y
# # needed for adding web repo in ubuntu
RUN apt-get install gnupg software-properties-common -y
# psycopg dep 
RUN apt-get install postgresql libpq-dev -y

# ## install qgis - software-properties-common needed
# RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key 51F523511C7028C3
# RUN add-apt-repository "deb https://qgis.org/ubuntu-ltr `lsb_release -c -s` main"
# RUN apt-get update
# RUN apt-get install qgis=1:3.* python3-qgis=1:3.* -y

# RUN wget -qO - https://qgis.org/downloads/qgis-2020.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
# RUN chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
# # RUN add-apt-repository "deb https://qgis.org/debian-ltr `lsb_release -c -s` main"
# RUN add-apt-repository "deb https://qgis.org/ubuntu-ltr `lsb_release -c -s` main"
# RUN apt-get update
# RUN apt-get install qgis=1:3.10.* python3-qgis=1:3.10.* -y

COPY arteliasite ./arteliasite
COPY Lamia ./Lamia
COPY arteliasitedocker/requirements.txt ./requirements.txt
# COPY test ./test
# COPY __init__.py .__init__.py

#Requirements
RUN apt-get install python3-pip -y
RUN pip3 install -r ./requirements.txt
RUN pip3 uninstall test

WORKDIR /usr/src/app/arteliasite

##node and yarn install
RUN apt-get install nodejs yarnpkg -y
RUN yarnpkg install
RUN yarnpkg prodd

##django operations
ENV  DJANGO_SETTINGS_MODULE arteliasite.settings.prod
RUN python3 manage.py collectstatic

#static npm dep
RUN cp -r /usr/src/app/arteliasite/node_modules/bootstrap /static/bootstrap
RUN cp -r /usr/src/app/arteliasite/node_modules/jquery /static/jquery
RUN cp -r /usr/src/app/arteliasite/node_modules/popper.js /static/popper.js 
RUN cp -r /usr/src/app/arteliasite/translations /static/translations

FROM nginx:latest

COPY --from=build /static/ /usr/src/app/static/
COPY arteliasitedocker/default.conf /etc/nginx/conf.d/default.conf






