FROM ubuntu:focal

# set work directory
WORKDIR /usr/src/Lamia

# uncomment for install behind artelias proxy
ARG http_proxy=http://10.15.102.50:3128
ARG https_proxy=http://10.15.102.50:3128

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH="/usr/src:${PATH}"

## INSTALLATION

# general dependancies
RUN apt-get update && apt-get install apt-utils sudo dialog dos2unix wget -y
# skipping prompt for keyboard conf
RUN DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration -y
# # needed for adding web repo in ubuntu
RUN apt-get install gnupg software-properties-common -y
# psycopg dep 
RUN apt-get install postgresql libpq-dev -y
# nginx
RUN apt install nginx -y
# python
RUN apt-get install python3-pip -y
# node 
RUN apt-get install nodejs yarnpkg -y

# ## install qgis - software-properties-common needed
RUN wget -qO - https://qgis.org/downloads/qgis-2020.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
RUN chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
# RUN add-apt-repository "deb https://qgis.org/debian-ltr `lsb_release -c -s` main"
RUN add-apt-repository "deb https://qgis.org/ubuntu-ltr `lsb_release -c -s` main"
RUN apt-get update
RUN apt-get install qgis=1:3.10.* python3-qgis=1:3.10.* -y

## COPYING

COPY arteliasite ./arteliasite
COPY config ./config
COPY qgisiface ./qgisiface
COPY api ./api
COPY arteliasitedocker/requirements.txt ./requirements.txt
COPY test ./test
COPY secrets/*.py ./secrets/
COPY __init__.py ./__init__.py
COPY __init__.py ../__init__.py

COPY arteliasitedocker/default.conf /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/sites-available/default
RUN rm /etc/nginx/sites-enabled/default

## PROCESSING

##Requirements

RUN pip3 install -r ./requirements.txt
# RUN pip3 uninstall test

##node and yarn actions
WORKDIR /usr/src/Lamia/arteliasite
RUN yarnpkg install
RUN yarnpkg prodd

##django operations
ENV  DJANGO_SETTINGS_MODULE arteliasite.settings.prod
RUN python3 manage.py migrate
RUN python3 manage.py makemigrations
RUN python3 manage.py collectstatic


#move static
# RUN mkdir /static/
# RUN cp -r /usr/src/Lamia/arteliasite/static/  /static/
RUN cp -r /usr/src/Lamia/arteliasite/node_modules/bootstrap /usr/src/Lamia/static/bootstrap
RUN cp -r /usr/src/Lamia/arteliasite/node_modules/jquery /usr/src/Lamia/static//jquery
RUN cp -r /usr/src/Lamia/arteliasite/node_modules/popper.js /usr/src/Lamia/static/popper.js 
RUN cp -r /usr/src/Lamia/arteliasite/translations /usr/src/Lamia/static/translations



EXPOSE 80
# CMD ["bash"]
# CMD ["gunicorn", "-b", "0.0.0.0:8085", "-w", "2", "arteliasite.wsgi"]
# CMD ["gunicorn", "-b", "localhost:8085", "-w", "2", "arteliasite.wsgi"]
# CMD ["service", "nginx", "start", ";","gunicorn", "-b", "localhost:8085", "-w", "2", "arteliasite.wsgi"]
WORKDIR /usr/src/Lamia/arteliasite
COPY arteliasitedocker/dockerfile_arteliasite_nginx_start.sh ./dockerfile_arteliasite_nginx_start.sh
# CMD ["dockerfile_arteliasite_nginx_start.sh"]
CMD ./dockerfile_arteliasite_nginx_start.sh





