FROM ubuntu:focal

# set work directory


# uncomment for install behind artelias proxy
ARG http_proxy=http://10.15.102.50:3128
ARG https_proxy=http://10.15.102.50:3128

# set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# general dependancies
RUN apt-get update && apt-get install apt-utils sudo dialog dos2unix wget -y
# skipping prompt for keyboard conf
RUN DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration -y
# # needed for adding web repo in ubuntu
RUN apt-get install gnupg software-properties-common -y

RUN wget -qO - https://qgis.org/downloads/qgis-2020.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
RUN chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
# RUN add-apt-repository "deb https://qgis.org/debian-ltr `lsb_release -c -s` main"
RUN add-apt-repository "deb https://qgis.org/ubuntu-ltr `lsb_release -c -s` main"
RUN apt-get update
RUN apt-get install qgis-server=1:3.10.* -y

RUN apt-get install apache2 libapache2-mod-fcgid -y

WORKDIR /
COPY qgisserver/projects ./projects

WORKDIR /etc/apache2
COPY arteliasitedocker/qgisserver/000-default.conf ./sites-available/000-default.conf
COPY arteliasitedocker/qgisserver/fcgid.conf ./mods-available/fcgid.conf

RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf
RUN a2enmod cgi

RUN echo 'Header set Access-Control-Allow-Origin "*"' >> /etc/apache2/apache2.conf
RUN a2enmod headers

EXPOSE 80

# CMD ["service", "apache2", "start"]
# apachectl -D FOREGROUND
CMD ["apachectl", "-D", "FOREGROUND"]







