# Generated by Django 3.0.8 on 2020-08-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamiacarto', '0004_auto_20200806_1424'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
